name: "CD (Continuous Delivery): main workflow"

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches: ['main', 'deploy/**']

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Run deploy
              run: |
                npm install
                npx vercel login
                npm run deploy:prod