name: "CI (integração continua): main workflow"

on:
    pull_request:
        type: [opened, synchronize]

jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Run installation
              run: npm install
            
            - name: Run linter
              run: npm run lint
