name: "CI (integração continua): primeira action"

on:
  # Aciona o fluxo de trabalho em eventos de solitação push ou pull mas apenas para a branch "main"
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

# Denição de fluxos de trabalhos que podem ser compostos por um ou mais fluxos que podem ser excutados em sequencia ou paralelamente
jobs:
  exemplo: # Job: exemplo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a list file
        run: ls -la
